version:

services:
  app:
    container_name: app
    build: .
    ports:
      - 3030:3030
    depends_on:
      - mysql_db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
    networks:
      - goapp

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
    networks:
      - goapp
volumes:
  mysql_db:

networks:
  goapp:
    driver: bridge
